version: '3.3'

services:

  db:
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    build: ../backend/
    container_name: foodgram-backend
    depends_on:
      - db
    env_file: ../.env
    volumes:
      - static:/app/static/
      - media:/app/media/
      - redoc:/app/api/docs/

  frontend:
    build: ../frontend
    container_name: foodgram-front
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - static:/var/html/static/
      - media:/var/html/media/
      - redoc:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
    restart: always

volumes:
  pg_data:
  static:
  media:
  redoc: