# Generated by Django 3.2.16 on 2024-08-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipe/images/', verbose_name='изображение'),
        ),
    ]
