# Generated by Django 3.2.16 on 2024-09-04 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_ingredient_unique_ingredient_in_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0.1, message='Время не может быть равно 0 или быть отрицательным.'), django.core.validators.MaxValueValidator(32000, message='Время приготовления не может превышать 32000 минут.')], verbose_name='время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0.01, message='Количество не может быть равно 0 или быть отрицательным.')], verbose_name='количество'),
        ),
    ]
