# Generated by Django 3.2.16 on 2024-09-12 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_auto_20240904_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0, message='Время не может быть меньше 0'), django.core.validators.MaxValueValidator(32000, message='Время приготовления не может превышать 32000 минут.')], verbose_name='время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0, message='Количество не может быть меньше 0')], verbose_name='количество'),
        ),
    ]
