# Generated by Django 3.2.16 on 2024-09-04 13:27

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('user', django.db.models.expressions.F('subscribed_to'))), name='user_cannot_subscribe_to_self'),
        ),
    ]
