# Generated by Django 3.2.16 on 2024-08-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=1, upload_to='avatar/', verbose_name='аватар'),
            preserve_default=False,
        ),
    ]
