# Generated by Django 3.2.16 on 2024-08-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='users/avatars/', verbose_name='аватар'),
        ),
    ]
