# Generated by Django 3.2.16 on 2024-09-04 13:30

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscription_user_cannot_subscribe_to_self'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='user_cannot_subscribe_to_self',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('user', django.db.models.expressions.F('subscribed_to')), _negated=True), name='user_cannot_subscribe_to_self'),
        ),
    ]
